# Generated by Django 2.2.5 on 2020-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20201204_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='address',
            field=models.CharField(default='Egypt Cairo', max_length=100),
        ),
        migrations.AddField(
            model_name='companies',
            name='name',
            field=models.CharField(default='Ahmed Eid', max_length=30),
        ),
        migrations.AddField(
            model_name='companies',
            name='phone',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
