# Generated by Django 2.2.5 on 2020-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20201204_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='phone',
            field=models.CharField(default='01234652582', max_length=15),
        ),
    ]
