# Generated by Django 2.2.5 on 2020-12-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
