# Generated by Django 2.2.5 on 2020-12-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_id',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant.companies'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_comp_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_rest_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='restaurant_id',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
