# Generated by Django 2.2.5 on 2020-12-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20201204_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.companies'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
