# Generated by Django 2.2.5 on 2020-12-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
