# Generated by Django 2.2.5 on 2020-12-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restaurant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
