# Generated by Django 2.2.5 on 2020-12-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.companies'),
        ),
    ]
