# Generated by Django 2.2.5 on 2020-12-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('IN_REQUEST', 'Request'), ('in_PREPARINGz', 'Preparing'), ('RECIVED', 'Received'), ('CANCELED', 'Cancel')], max_length=30),
        ),
    ]
