# Generated by Django 2.2.5 on 2020-12-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_auto_20201205_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('IN_REQUEST', 'Request'), ('IN_PREPARING', 'Preparing'), ('RECIVED', 'Received'), ('CANCELED', 'Cancel')], max_length=30),
        ),
    ]
